# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_trello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='brief_description',
            field=models.CharField(max_length=100),
        ),
    ]
