# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_sponsors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='trello',
            field=models.URLField(blank=True),
        ),
    ]
