# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:13
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_avatar',
            field=models.ImageField(blank=True, upload_to=account.models.image_upload_path),
        ),
    ]
