# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_school_school_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
