# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160422_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_view_students', 'Can View Students'), ('can_view_projects', 'Can View Projects'), ('can_view_teams', 'Can View Teams'), ('can_view_employees', 'Can View Employees')), 'verbose_name': 'employee'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_view_students', 'Can View Students'), ('can_view_projects', 'Can View Projects'), ('can_view_teams', 'Can View Teams')), 'verbose_name': 'student'},
        ),
    ]
